name: Auto Pluto MX Update

on:
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24' # Forzamos la versión compatible actual del servidor
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Run Scraper
      run: node index.js

    - name: Commit and Push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add output/*
        git commit -m "Actualizando listas M3U8" || exit 0
        git push
