name: Auto Pluto MX Update

on:
  workflow_dispatch: # Esto activa el botón para iniciarlo manualmente

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run Scraper
      run: node index.js

    - name: Commit and Push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add output/*
        git commit -m "Actualizando listas M3U8" || exit 0
        git push
